### PR TITLE
add live apy to home

### PR DESCRIPTION
**Pull request by vujevits**

### CODE REVIEW

**Comment by kyriediculous** [comment]
Looks good at first glance, will do some manual testing on this when the contracts are redeployed

**Comment by kyriediculous** [comment]
rebased this on top of master to redeploy the preview with the latest contract addresses

**Comment by kyriediculous** [comment]
Looks like I still have to refresh before the rewards show the correct amount. 

To reproduce: 

Request 100 LPT from faucet
Approve 100 LPT for stake
Deposit 100 LPT
See Stake is 100 LPT ✅ 
See Rewards is 100 LPT 🔴 
Refresh
Rewards is now 0 LPT

**Comment by kyriediculous** [comment]
I Believe one potential solution is to refetch the subgraph query until `data.tenderizerStake` gets updates with the deposit amount and only re-render the component (or at least the specific infocard) when that is the case

**Comment by vujevits** [comment]
fixing rewards updating issue in a separate PR

**Pull request merged**
